config/routes.rb
Rails.application.routes.draw do
  get 'shopping_lists/index'
  devise_for :users

  # define resources
  resources :foods
  resources :recipes, except: [:edit] do
    resources :recipe_foods, only: %i[new create edit update destroy]
  end

  # define root
  root to: 'recipes#public_index'
  get '/general_shopping_list' , to: 'shopping_lists#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods

  validates :name, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :measurement_unit, presence: true, inclusion: { in: %w[g l units] }
  validates :quantity, presence: true, numericality: { greater_than: 0 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods

  validates :name, presence: true
  validates :preparation_time, presence: true, numericality: { greater_than: 0 }
  validates :cooking_time, presence: true, numericality: { greater_than: 0 }
  validates :description, presence: true
  validates :public, inclusion: { in: [true, false] }
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :quantity, presence: true, numericality: { greater_than: 0 }
  validates :recipe_id, presence: true
  validates :food_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!
  def index
    @foods = Food.where(user: current_user)
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    @food.user = current_user

    if @food.save
      redirect_to foods_path, notice: 'Food was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to foods_path, notice: 'Food was successfully deleted.'
  end

  private

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity, :user_id)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :set_recipe
  before_action :set_recipe_food, only: %i[edit update destroy]
  before_action :set_foods, only: %i[new edit create update]

  def new
    @recipe_food = @recipe.recipe_foods.build
  end

  def create
    @recipe_food = @recipe.recipe_foods.find_by(food_id: recipe_food_params[:food_id])
    if @recipe_food
      # Update quantity if RecipeFood already exists
      @recipe_food.quantity += recipe_food_params[:quantity].to_i
    else
      # Build new RecipeFood if it doesn't exist
      @recipe_food = @recipe.recipe_foods.build(recipe_food_params)
    end

    if @recipe_food.save
      redirect_to @recipe, notice: 'Ingredient added successfully!'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @recipe_food.update(recipe_food_params)
      redirect_to @recipe, notice: 'Ingredient updated successfully!'
    else
      render :edit
    end
  end

  def destroy
    @recipe_food.destroy
    redirect_to @recipe, notice: 'Ingredient removed successfully!'
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:recipe_id])
  end

  def set_recipe_food
    @recipe_food = RecipeFood.find(params[:id])
  end

  def set_foods
    @foods = Food.where(user: current_user)
  end

  def recipe_food_params
    params.require(:recipe_food).permit(:food_id, :quantity)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: %i[public_index]
  before_action :set_recipe, only: %i[edit update destroy]

  def index
    @recipes = Recipe.where(user: current_user)
  end

  def public_index
    @recipes = Recipe.includes(recipe_foods: :food).where(public: true).order('created_at DESC')
  end

  def show
    flash.clear

    @recipe = Recipe.includes(:recipe_foods).find(params[:id])
    @recipe_food = @recipe.recipe_foods.includes(:food)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user

    if @recipe.save
      redirect_to @recipe, notice: 'Recipe was successfully created.'
    else
      render :new
    end
  end

  def update
    @recipe.update(recipe_params)
    redirect_to @recipe, notice: 'Recipe was successfully updated.'
  end

  def destroy
    @recipe.destroy
    redirect_to recipes_path, notice: 'Recipe was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public, :user_id)
  end
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
  include ShoppingListsHelper
  before_action :authenticate_user!

  def index
    @recipes = Recipe.includes(recipe_foods: :food).where(user: current_user)
    @available_foods = Food.where(user: current_user)
    @missing_foods, @total_missing_items, @total_price = calculate_missing_foods(@recipes, @available_foods)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def convert_unit(unit)
    case unit
    when 'g'
      'grams'
    when 'l'
      'litres'
    when 'units'
      'units'
    else
      unit
    end
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shopping_lists_helper.rb
module ShoppingListsHelper
  def calculate_missing_foods(recipes, available_foods)
    missing_foods = []
    total_missing_items = 0
    total_price = 0

    recipes.each do |recipe|
      recipe.recipe_foods.each do |recipe_food|
        food_name = recipe_food.food.name
        required_quantity = recipe_food.quantity

        available_food = available_foods.find { |food| food.name == food_name }

        if available_food
          available_quantity = available_food.quantity
          missing_quantity = [required_quantity - available_quantity, 0].max

          if missing_quantity.positive?
            missing_foods << {
              name: food_name,
              quantity: missing_quantity,
              price: available_food.price # Assuming price is in the Food model
            }
            total_missing_items += 1
            total_price += missing_quantity * available_food.price
          end
        else
          missing_foods << {
            name: food_name,
            quantity: required_quantity,
            price: recipe_food.food.price # If price is not in the Food model
          }
          total_missing_items += 1
          total_price += required_quantity * recipe_food.food.price
        end
      end
    end

    [missing_foods, total_missing_items, total_price]
  end
end

app/views/foods/_form.html.erb
<%= form_for @food do |f| %>
  
  <div class="field">
    <%= f.label :name, class: "hidden" %><br />
    <%= f.text_field :name, autofocus: true, autocomplete: "name", placeholder: "Name", class:
                       'mt-1 block w-full rounded-md border border-black shadow-sm focus:border-black' %>
  </div>

  <div class="field">
    <%= f.label :price, class: "hidden" %><br>
    <%= f.number_field :price, step: :any, placeholder: "Price", class:
                       'mt-1 block w-full rounded-md border border-black shadow-sm focus:border-black' %>
  </div>

  <div class="field">
    <%= f.label :measurement_unit, class: "hidden" %><br>
    <%= f.select :measurement_unit, [['grams', 'g'], ['litres', 'l'], ['units', 'units']], {}, placeholder: "Measurement Unit", class:
                       'mt-1 block w-full rounded-md border border-black shadow-sm focus:border-black' %>
  </div>

  <div class="field">
    <%= f.label :quantity, class: "hidden" %><br>
    <%= f.number_field :quantity, step: :any, placeholder: "Quantity", class:
                       'mt-1 block w-full rounded-md border border-black shadow-sm focus:border-black' %>
  </div>

  <div class="actions my-5">
    <%= f.submit (@food.persisted? ? "Update" : "Add"), class:
              'bg-gray-500 text-white w-full m-0 border border-black shadow-black p-2 rounded hover:shadow-none cursor-pointer' %>
  </div>
<% end %>

app/views/foods/index.html.erb
<div class="w-full mx-auto flex flex-col justify-center">
  <div class="flex justify-end">
    <%=
      link_to 'Add Food',
              new_food_path,
              class:
                'text-center no-underline m-0 border border-black shadow-black p-2 rounded hover:shadow-none cursor-pointer'
    %>
  </div>

  <table class="table-auto w-full border border-black">
    <thead class="font-medium dark:bg-neutral-300">
      <tr>
        <th class="px-4 py-2 text-center">Food</th>
        <th class="px-4 py-2 text-center">Measurement nit</th>
        <th class="px-4 py-2 text-center">Unit price</th>
        <th class="px-4 py-2 text-center">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @foods.each.with_index do |food, index| %>
        <tr class="<%= cycle('dark:bg-neutral-100', '') %>">
          <td class="px-4 py-2 text-center"><%= food.name %></td>
          <td class="px-4 py-2 text-center">
            <%= convert_unit(food.measurement_unit) %>
          </td>
          <td class="px-4 py-2 text-center">
            <%= number_to_currency(food.price) %>
          </td>
          <td class="px-4 py-2 text-center">
            <%=
              button_to 'Delete',
                        food_path(food),
                        method: :delete,
                        data: {
                          turbo_confirm: 'Are you sure?',
                        },
                        class: 'text-blue-500 underline'
            %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/foods/new.html.erb
<div class="w-full mx-auto flex flex-col justify-center">
<h2 class="text-center my-0">Add new Food</h2>

<%= render 'form' %>

</div>

app/views/layouts/_navbar.html.erb
<nav class="w-full flex justify-between items-center">
  <div class="border border-black rounded-full">
    <%= image_tag "logo.png", class: "m-0 w-12 h-auto rounded-full" %>
  </div>
  <div class="flex justify-between items-center gap-5">
    <ul class="flex justify-between gap-5 list-none">
      <li><%= link_to "Public recipes", root_path, class: "no-underline hover:active focus:active #{'active' if current_page?(root_path)}" %></li>
      <% if user_signed_in? %>
        <li><%= link_to "Recipes", recipes_path, class: "no-underline hover:active focus:active #{'active' if current_page?(recipes_path)}" %></li>
        <li><%= link_to "Foods", foods_path, class: "no-underline hover:active focus:active #{'active' if current_page?(foods_path)}" %></li>
        <li><%= link_to "Shopping list", general_shopping_list_path, class: "no-underline hover:active focus:active #{'active' if current_page?(general_shopping_list_path)}" %></li>
      <% end %>
    </ul>

    <% if user_signed_in? %>
      <%=
        button_to(
          'Sign Out',
          destroy_user_session_path,
          method: :delete,
          class:
              'text-center no-underline w-full m-0 border border-black shadow-black p-2 rounded hover:shadow-none cursor-pointer'
        )
      %>
    <% else %>
      <% unless current_page?(new_user_session_path) or current_page?(new_user_registration_path) %>
        <div class="flex gap-5">
      <%=
        button_to(
          'Sign in',
          new_user_session_path,
          method: :get,
          class: 'text-center no-underline w-full m-0 border border-black shadow-black p-2 rounded hover:shadow-none cursor-pointer'
        )
      %>
      <%=
        button_to(
          'Sign up',
          new_user_registration_path,
          method: :get,
          class: 'text-center no-underline w-full m-0 border border-black shadow-black p-2 rounded hover:shadow-none cursor-pointer'
        )
      %>
      </div>
    <% end %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipe App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%=
      stylesheet_link_tag 'tailwind', 'inter-font', 'data-turbo-track': 'reload'
    %>

    <%= stylesheet_link_tag 'application', 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>
    <% favicon_link_tag 'favicon.ico', type: 'image/x-icon', rel: 'shortcut icon' %>
  </head>

  <body class="prose mx-auto px-5">
  <%= render "layouts/navbar" %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <main class="container mx-auto mt-5 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/recipe_foods/_form.html.erb
<%= form_for([@recipe, @recipe_food]) do |f| %>
  
  <div class="field">
    <%= f.label :food_id, class: "hidden" %><br />
    <%= f.select :food_id, @foods.collect { |food| [food.name, food.id] }, include_blank: true, prompt: "Select Ingredient", class:
                       'mt-1 block w-full rounded-md border border-black shadow-sm focus:border-black' %>
  </div>

  <div class="field">
    <%= f.label :quantity, class: "hidden" %><br>
    <%= f.number_field :quantity, step: :any, placeholder: "Quantity", class:
                       'mt-1 block w-full rounded-md border border-black shadow-sm focus:border-black' %>
  </div>

  <div class="actions my-5">
    <%= f.submit (@recipe_food.persisted? ? "Update" : "Add"), class:
              'bg-gray-500 text-white w-full m-0 border border-black shadow-black p-2 rounded hover:shadow-none cursor-pointer' %>
  </div>
<% end %>

app/views/recipe_foods/edit.html.erb
<div class="w-full mx-auto flex flex-col justify-center">
<h2 class="text-center my-0">Modify Ingredient</h2>

<%= render 'form' %>

</div>

app/views/recipe_foods/new.html.erb
<div class="w-full mx-auto flex flex-col justify-center">
<h2 class="text-center my-0">Add Ingredient</h2>

<%= render 'form' %>

</div>

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
  
  <div class="field">
    <%= f.label :name, class: "hidden" %><br />
    <%= f.text_field :name, autofocus: true, autocomplete: "name", placeholder: "Name", class:
                       'mt-1 block w-full rounded-md border border-black shadow-sm focus:border-black' %>
  </div>

  
  <div class="field">
    <%= f.label :preparation_time, class: "hidden" %><br>
    <%= f.number_field :preparation_time, step: :any, placeholder: "Preparation time in hours", class:
                       'mt-1 block w-full rounded-md border border-black shadow-sm focus:border-black' %>
  </div>

  <div class="field">
    <%= f.label :cooking_time, class: "hidden" %><br>
    <%= f.number_field :cooking_time,step: :any, placeholder: "Cooking time in hours", class:
                       'mt-1 block w-full rounded-md border border-black shadow-sm focus:border-black' %>
  </div>

  <div class="field">
    <%= f.label :description, class: "hidden" %><br>
    <%= f.text_area :description, placeholder: "Description", class:
                       'mt-1 block w-full rounded-md border border-black shadow-sm focus:border-black' %>
  </div>

  <div class="field flex items-center">
    <%= f.label :public %>:<br>
    <%= f.check_box :public, class: "ml-5" %>
  </div>


  <div class="actions my-5">
    <%= f.submit (@recipe.persisted? ? "Update" : "Add"), class:
              'bg-gray-500 text-white w-full m-0 border border-black shadow-black p-2 rounded hover:shadow-none cursor-pointer' %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<div class="w-full mx-auto flex flex-col justify-center">
<h2 class="text-center my-0">Edit Recipe</h2>

<%= render 'form' %>

</div>

app/views/recipes/index.html.erb
<div class="w-full mx-auto flex flex-col justify-center">
  <%= link_to "Add Recipe",  new_recipe_path, class: "my-5 self-end no-underline border border-black shadow-black p-2 rounded hover:shadow-none cursor-pointer" %>
  <div class="flex flex-col">
    <% if @recipes.empty? %>
      <p class="text-center">No recipes found.</p>
    <% else %>
      <% @recipes.each do |recipe| %>
        <div class="flex border border-black mb-2 gap-5 p-3">
          <div class="shrink-0 flex flex-col justify-between">
            <%= link_to recipe_path(recipe), class: "no-underline" do %>
              <h3 class="m-0"><%= recipe.name %></h3>
            <% end %>
            <%=
              button_to 'Remove',
                        recipe,
                        method: :delete,
                        data: {
                          turbo_confirm: 'Are you sure?',
                        }, class: "text-blue-500 underline"
            %>
          </div>
          <p class="m-0">
            <%= recipe.description %>
          </p>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="w-full mx-auto flex flex-col justify-center">
<h2 class="text-center my-0">Add new Recipe</h2>

<%= render 'form' %>

</div>

app/views/recipes/public_index.html.erb
<div class="w-full mx-auto flex flex-col justify-center">
  <h2 class="text-center mt-0">Public Recipes</h2>

  <div class="flex flex-col">
    <% @recipes.each do |recipe| %>
      <%= link_to recipe_path(recipe), class: "no-underline" do %>
        <div class="flex border border-black mb-2 gap-5 p-3">
          <div>
            <h3 class="m-0"><%= recipe.name %></h3>
            <p class="m-0"><%= recipe.user.name %></p>
          </div>
          <div>
            <% total_items = recipe.recipe_foods.size %>
            <% total_price = recipe.recipe_foods.sum { |rf| rf.quantity * rf.food.price } %>
            <p class="m-0">Total food items: <%= total_items %></p>
            <p class="m-0">Total price: $<%= total_price %></p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="w-full mx-auto flex flex-col justify-center">
  <h2 class="text-center my-0"><%= @recipe.name %></h2>
  <div class="flex justify-between">
    <p>
      Preparation Time: <%= @recipe.preparation_time %> <%=
        'hour'.pluralize(@recipe.preparation_time)
      %>
    </p>
    <% if current_user == @recipe.user %>
      <%= form_with(model: @recipe, html: { class: "relative inline-block w-10 align-middle select-none transition duration-200 ease-in" }) do |form| %>
        <%=
          form.hidden_field :public, value: @recipe.public ? 'false' : 'true'
        %>
        <%=
          form.submit '',
                      id: 'toggle',
                      role: 'switch',
                      aria_checked: @recipe.public ? 'true' : 'false',
                      class:
                        "toggle-checkbox absolute block w-6 h-6 rounded-full bg-white border-2 border-black appearance-none cursor-pointer #{@recipe.public ? 'translate-x-full' : 'translate-x-0'}",
                      onclick: 'this.form.submit()'
        %>
        <%=
          label_tag 'toggle',
                    '',
                    class:
                      "toggle-label block overflow-hidden h-6 rounded-full cursor-pointer border-2 border-black #{@recipe.public ? 'bg-green-500' : 'bg-red-500'}"
        %>
      <% end %>
    <% end %>
  </div>
  <div class="flex justify-between">
    <p>
      Cooking Time: <%= @recipe.cooking_time %> <%=
        'hour'.pluralize(@recipe.cooking_time)
      %>
    </p>
  </div>

  <div class="flex justify-between">
    <h3>Steps go here...</h3>
  </div>

  <% if current_user == @recipe.user %>
    <div class="flex justify-between border-b-2 border-gray-500 pb-5">
      <%=
        link_to 'Generate Shopping list',
                general_shopping_list_path,
                class:
                  'm-0 no-underline border border-black shadow-black p-2 rounded hover:shadow-none cursor-pointer'
      %>
      <%=
        link_to 'Add Ingredient',
                new_recipe_recipe_food_path(@recipe),
                class:
                  'm-0 no-underline border border-black shadow-black p-2 rounded hover:shadow-none cursor-pointer'
      %>
    </div>
  <% end %>

  <table class="table-auto w-full border border-black">
    <thead class="font-medium dark:bg-neutral-300">
      <tr>
        <th class="px-4 py-2 text-center">Food</th>
        <th class="px-4 py-2 text-center">Quantity</th>
        <th class="px-4 py-2 text-center">Value</th>
        <th class="px-4 py-2 text-center">Action</th>
      </tr>
    </thead>
    <tbody>
      <% if @recipe_food.empty? %>
        <tr class="dark:bg-neutral-100">
          <td class="px-4 py-2 text-center" colspan="4">
            No ingredients added
          </td>
        </tr>
      <% else %>
        <% @recipe_food.each.with_index do |ingredient, index| %>
          <tr class="<%= cycle('dark:bg-neutral-100', '') %>">
            <td class="px-4 py-2 text-center"><%= ingredient.food.name %></td>
            <td class="px-4 py-2 text-center">
              <%= ingredient.quantity %><%=
                ingredient.food.measurement_unit == 'units' ? ' ' : ''
              %><%= ingredient.food.measurement_unit %>
            </td>
            <td class="px-4 py-2 text-center">
              <%=
                number_to_currency(ingredient.food.price * ingredient.quantity)
              %>
            </td>
            <td class="px-4 text-center flex justify-center gap-3">
              <% if current_user == @recipe.user %>
                <%=
                  link_to 'Modify',
                          edit_recipe_recipe_food_path(@recipe, ingredient),
                          class: 'text-blue-500'
                %>
                <%=
                  button_to 'Remove',
                            recipe_recipe_food_path(@recipe, ingredient),
                            method: :delete,
                            data: {
                              turbo_confirm: 'Are you sure?',
                            },
                            class: 'text-blue-500 underline'
                %>
              <% end %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/shopping_lists/index.html.erb
<div class="w-full mx-auto flex flex-col justify-center">
  <h2 class="text-center mt-0">Shopping List</h2>

   <div class="flex justify-between">
    <p>
      Amount of Food items to buy: <%= @total_missing_items %>
    </p>

    <p>
      Total value of food needed: $<%= @total_price %>
    </p>
  </div>


  <table class="table-auto w-full border border-black">
    <thead class="font-medium dark:bg-neutral-300">
      <tr>
        <th class="px-4 py-2 text-center">Food</th>
        <th class="px-4 py-2 text-center">Quantity</th>
        <th class="px-4 py-2 text-center">Price</th>
      </tr>
    </thead>
    <tbody>
      <% @missing_foods.each.with_index do |food, index| %>
      <tr class="<%= cycle('dark:bg-neutral-100', '') %>">
        <td class="px-4 py-2 text-center"><%= food[:name] %></td>
        <td class="px-4 py-2 text-center"><%= food[:quantity] %></td>
        <td class="px-4 py-2 text-center"><%= number_to_currency(food[:price]) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>